version: '3.9'
services:
  elasticsearch:
    image: ElasticImages
    container_name: ElasticContainerName
    restart: always 
    environment:
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ElasticDATADIR/data:/var/lib/elasticsearch
      - ElasticDATADIR/logs:/var/log/elasticsearch
      - ./elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
