version: '3.9'
services:
  mysql-server:
    image: mysql:5.7.34
    container_name: MYSQLCONTAINERNAME
    command: --character-set-server=utf8  --collation-server=utf8_bin
    #restart: always 
    environment:
      - MYSQL_DATABASE=MYSQLDATABASE
      - MYSQL_USER=MYSQLUSER
      - MYSQL_PASSWORD=MYSQLPASSWORD
      - MYSQL_ROOT_PASSWORD=MYSQLROOTPASSWORD
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    network_mode: bridge

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: MYSQLDATADIR
