version: '3'
services:
  redis:
    image: REDISIMAGES
    container_name: REDISContainerName
    volumes:
      - data:/data
      - logs:/logs
      - ./redis.conf:/etc/redis.conf
    ports:
      - 6379:6379
    sysctls:
      - net.core.somaxconn=65535 
    command: redis-server /etc/redis.conf
    network_mode: bridge

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: REDISDATA
  logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: REDISLOGS
