#!/bin/bash

. `pwd`/config.txt

function help(){

    cat <<- EOF
		Installation Guide:

		ENV
		OS: CentOS 7
		nginx: 1.20.0
		PHP: 7.4.16
		MySQL: 5.7.34

		Custom parameter configuration:

			config-example.conf

			key1=value1
			...........
			keyn=valuen
		pre-install:
		sh deploy prenv  (install docker and docker-compose)
		install:
		sh deplopy [mysql|magento2|all]
		uninstall:
		sh deploy [del_mysql|del_magento2|del_all]
		set Permission:
		sh deploy permission

	EOF
    exit 0

}

function prenv(){


        sudo yum install -y yum-utils
	sudo yum-config-manager --add-repo http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo

        sudo yum -y install docker-ce docker-ce-cli containerd.io 

        systemctl start docker
        systemctl enable docker


        #sudo curl -L "https://github.com/docker/compose/releases/download/1.29.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo  cp ./bin/docker-compose /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
}

function uninstall(){
	yum -y remove docker-ce docker-ce-cli containerd.io
	rm -f /etc/yum.repos.d/docker-ce.repo
	rm -f /usr/local/bin/docker-compose
}

function mysql(){
	if [ ! -d $MYSQL_DATA ];then
		mkdir $MYSQL_DATA
	fi

	MYSQLDIR=$ROOTDIR/mysql
	DOCKERCOMPOSEFILE=$MYSQLDIR/docker-compose.yml

	if [ -f $DOCKERCOMPOSEFILE ];then
		rm -f $DOCKERCOMPOSEFILE
		cp $ROOTDIR/template/mysql.yml $DOCKERCOMPOSEFILE
	else
		cp $ROOTDIR/template/mysql.yml $DOCKERCOMPOSEFILE
	fi
	sed -i "s/MYSQLDATABASE/$MYSQLDATABASE/g" $DOCKERCOMPOSEFILE
	sed -i "s/MYSQLUSER/$MYSQLUSER/g" $DOCKERCOMPOSEFILE
	sed -i "s/MYSQLPASSWORD/$MYSQLPASSWORD/g" $DOCKERCOMPOSEFILE
	sed -i "s/MYSQLROOTPASSWORD/$MYSQLROOTPASSWORD/g" $DOCKERCOMPOSEFILE
	sed -i "s/MYSQLDATADIR/$MYSQLDATADIR/g" $DOCKERCOMPOSEFILE

	if test -z $MYSQLCONTAINERNAME;then
		MYSQLCONTAINERNAME="mysql_server"
		sed -i "s/MYSQLCONTAINERNAME/$MYSQLCONTAINERNAME/g" $DOCKERCOMPOSEFILE
	else
		sed -i "s/MYSQLCONTAINERNAME/$MYSQLCONTAINERNAME/g" $DOCKERCOMPOSEFILE

	fi
	cd $MYSQLDIR
	docker-compose up -d
}

function del_mysql(){
	cd $ROOTDIR/mysql
	docker-compose down
}

function magento2(){
	if [ ! -d $WWW_DATA ];then
	        mkdir $WWW_DATA
	fi

	MAGENTO2DIR=$ROOTDIR/magento2
	DOCKERCOMPOSEFILE=$MAGENTO2DIR/docker-compose.yml

	if [ -f $DOCKERCOMPOSEFILE ];then
		rm -f $DOCKERCOMPOSEFILE
		cp $ROOTDIR/template/magento2.yml $DOCKERCOMPOSEFILE
	else
		cp $ROOTDIR/template/magento2.yml $DOCKERCOMPOSEFILE
	fi
	sed -i "s/MAGENTO2IMAGES/$MAGENTO2IMAGES/g" $DOCKERCOMPOSEFILE
	sed -i "s/MagentoContainerName/$MagentoContainerName/g" $DOCKERCOMPOSEFILE
	sed -i "s/WWWDATA/$WWWDATA/g" $DOCKERCOMPOSEFILE

	cd $MAGENTO2DIR
	docker-compose up -d
}
function del_magento2(){
	cd $ROOTDIR/magento2
	docker-compose down
}

function redis(){
	REDISDIR=$ROOTDIR/redis
	DOCKERCOMPOSEFILE=$REDISDIR/docker-compose.yml

        if [ -f $DOCKERCOMPOSEFILE ];then
                rm -f $DOCKERCOMPOSEFILE
                cp $ROOTDIR/template/redis.yml $DOCKERCOMPOSEFILE
	else
		cp $ROOTDIR/template/redis.yml $DOCKERCOMPOSEFILE
        fi
        sed -i "s/REDISIMAGES/$REDISIMAGES/g" $DOCKERCOMPOSEFILE
        sed -i "s/REDISContainerName/$REDISContainerName/g" $DOCKERCOMPOSEFILE

	cd $REDISDIR
	docker-compose up -d
}

function del_redis(){
	cd $ROOTDIR/redis
	docker-compose down
}

function elasticsearch(){
	if [ ! -d $Elastic_DATA_DIR ];then
	        mkdir $Elastic_DATA_DIR/{data,logs}
	fi

	ELASTICDIR=$ROOTDIR/elasticsearch
	DOCKERCOMPOSEFILE=$ELASTICDIR/docker-compose.yml

        if [ -f $DOCKERCOMPOSEFILE ];then
                rm -f $DOCKERCOMPOSEFILE
                cp $ROOTDIR/template/elasticsearch.yml $DOCKERCOMPOSEFILE
	else
		cp $ROOTDIR/template/elasticsearch.yml $DOCKERCOMPOSEFILE
        fi

        sed -i "s/ElasticImages/$ElasticImages/g" $DOCKERCOMPOSEFILE
        sed -i "s/ElasticDATADIR/$ElasticDATADIR/g" $DOCKERCOMPOSEFILE
        sed -i "s/ElasticContainerName/$ElasticContainerName/g" $DOCKERCOMPOSEFILE

	cd $ELASTICDIR
	docker-compose up -d
}

function del_elasticsearch(){
	cd $ROOTDIR/elasticsearch
	docker-compose down
}

function ls(){
	docker ps
}

function restart(){
	for i in `docker ps | awk '{if (NR>2) {print $1}}'`;do
		docker restart $i
	done
}

function setPermission(){
	
	# $1 = container_name
	# path="/usr/share/nginx/html"
	
	container_name=$MagentoContainerName
	
	path=$M2PATH

	dir="var generated vendor pub/static pub/media app/etc"
	
	docker_cmd="docker exec -it $container_name"

	$docker_cmd chown -R nginx.nginx $path
	
	for i in $dir
	do
	        $docker_cmd find $path/$i -type f -exec chmod u+w {} +
	        $docker_cmd find $path/$i -type d -exec chmod u+w {} +
	        $docker_cmd find $path/$i -type f -exec chmod g+w {} +
	        $docker_cmd find $path/$i -type d -exec chmod g+ws {} +
	done
}

case $1 in
	"help")
	help	
	;;
	"prenv")
	prenv
	;;
	"ls")
	ls
	;;
	"setPermission")
	setPermission
	;;
	"restart")
	restart
	;;
	"mysql")
	mysql
	;;
	"magento2")
	magento2
	;;
	"redis")
	redis
	;;
	"elasticsearch")
	elasticsearch
	;;
	"all")
	mysql
	redis
	elasticsearch
	magento2
	;;
	"del_mysql")
	del_mysql
	;;
	"del_magento2")
	del_magento2
	;;
	"del_redis")
	del_redis
	;;
	"del_elasticsearch")
	del_elasticsearch
	;;
	"del_all")
	del_magento2
	del_redis
	del_elasticsearch
	del_mysql
	;;
	"uninstall")
	uninstall
	;;
	*)
	;;
esac
