version: '3.9'

services:
  magento2:
    image: m3:v7
    container_name: m2_web_new
    volumes:
      - ./cron:/var/spool/cron
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./php/php.ini:/etc/php.ini
      - ./php/php-fpm.conf:/etc/php-fpm.conf
      - ./php/www.conf:/etc/php-fpm.d/www.conf
      - ./php/10-opcache.ini:/etc/php.d/10-opcache.ini

    ports:
     - "80:80"
     - "443:443"
    network_mode: bridge
