version: '3.9'
services:
  elasticsearch:
    image: elasticsearch:7.12.1
    container_name: m2_elastic
    restart: always 
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /data/es_data/data:/usr/share/elasticsearch/data
      - /data/es_data/logs:/usr/share/elasticsearch/logs
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    network_mode: bridge
