version: '3.9'

services:
  magento2:
    image: hhank/m2:v1.2.3
    container_name: m2_web
    volumes:
      - www:/app
      - logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./php/php.ini:/etc/php.ini
      - ./php/php-fpm.conf:/etc/php-fpm.conf
      - ./php/www.conf:/etc/php-fpm.d/www.conf

    ports:
     - "80:80"
     - "443:443"
    network_mode: bridge


volumes:
  www:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/www_data
  logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/www_logs
