version: '3.9'
services:
  mysql-server:
    image: mysql:5.7.34
    container_name: m2_mysql
    command: --character-set-server=utf8  --collation-server=utf8_bin
    restart: always 
    environment:
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=m2user
      - MYSQL_PASSWORD=m2User123a@
      - MYSQL_ROOT_PASSWORD=m2User123a@
    ports:
      - 3306:3306
    volumes:
      - /data/mysql_data:/var/lib/mysql
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
